# (20) conv latents:  first step

**Motivation**: host = ```any```, device = ```cuda:0``` <br>

In [1]:
# HIDE CODE


import os, sys
from IPython.display import display

# tmp & extras dir
git_dir = os.path.join(os.environ['HOME'], 'Dropbox/git')
extras_dir = os.path.join(git_dir, 'jb-progress-2025/_extras')
fig_base_dir = os.path.join(git_dir, 'jb-progress-2025/figs')
tmp_dir = os.path.join(git_dir, 'jb-progress-2025/tmp')

# GitHub
sys.path.insert(0, os.path.join(git_dir, '_iclr_ipvae'))
from figures.convergence import plot_convergence
from main.config_defaults import default_configs
from figures.fighelper import *
from main.train import *

# warnings, tqdm, & style
warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=UserWarning)
from rich.jupyter import print
%matplotlib inline
set_style()

In [2]:
device_idx = 0
device = f'cuda:{device_idx}'

print(f"device: {device}  ———  host: {os.uname().nodename}")

device: cuda:0  ———  host: yoru

## conv arithmetic

In [3]:
from base.helper import conv_arithmetic

In [4]:
df = conv_arithmetic(
    input_size=8,
    output_size=16,
    # kernel_size=None,
    stride=1,
    padding=0,
    deconv=True,
)
df

     mode  computed    parameter  value
0  deconv     False   input_size      8
1  deconv     False  output_size     16
2  deconv      True  kernel_size      9
3  deconv     False       stride      1
4  deconv     False      padding      0

In [5]:
print(df.to_string(index=False))

  mode  computed   parameter  value
deconv     False  input_size      8
deconv     False output_size     16
deconv      True kernel_size      9
deconv     False      stride      1
deconv     False     padding      0

In [6]:
df.loc[df['computed']]

     mode  computed    parameter  value
2  deconv      True  kernel_size      9